### ISSUE TITLE
how to install this on ubuntu 20.04 server?

### ISSUE THREAD

**Issue by ghost** [erhant/simple-blockexplorer#1]
Hi, can we have a step by step idiots guide please. I read the readme. Yarn? Yarn what? I did git clone https://github.com/erhant/simple-blockexplorer.git. I'm now looking at a simple-blockexplorer directory, and no clue how to connect to my evm based rpc on port 10002.

Thanks

**Comment by RedWilly** [comment]
install yarn first, 

just search how to install yarn on your windows or linux/ubuntu

**Comment by ghost** [comment]
Thanks for the reply. Even just putting my rpc details in on the sbe web page, I can't get it to scrape the blocks. I tried the http and the https addresses, with the port specified as well. It works on Ethereum, and also on binance, just not on any of the 3 custom chains I tried. Rpc for one of them is https://chad2chain.org Another is https://mainnet.poochain.co/rpc both are EVM based (Polygon-edge)

Thanks, Nex

**Comment by erhant** [comment]
Hey, does the issue still persist? 

Regardless, I plan on making a re-write of this thing using SolidJS + Tailwind with a much more lightweight approach, and easier customizability and stuff. I will let you know within this issue when that happens.

**Comment by erhant** [comment]
Also will use Bun runtime for speeeeeeeed :)

**Comment by ghost** [comment]
Hi, I ended up using Blockscout for my polygon-edge chain. It's massively harder to set up than yours, but it's working fine. I customised the colours, page layout and coin name. It also has a contract verifier running.

**Comment by erhant** [comment]
Yea that one is way harder, + uses db as well iirc.

Maybe I could implement their schemas (or a small subset of them) for SQlite and use Bun's API for that, would be much faster & act as a self-hosted block explorer with minimal develpoment efforts; maybe sometime.

Anyways, thanks for trying this repo!

**Comment by ghost** [comment]
The db is horrible to set up, and it takes so long to sync. I'm half way
through a 12 million block chain, and it has been 2 months already...

I hope yours is more successful!
